(*
   Copyright (c) 2026 Gaëtan Lopez <glopez@irif.fr>

   Permission is hereby granted, free of charge, to any person obtaining a copy
   of this software and associated documentation files (the "Software"), to deal
   in the Software without restriction, including without limitation the rights
   to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
   copies of the Software, and to permit persons to whom the Software is
   furnished to do so, subject to the following conditions:

   The above copyright notice and this permission notice shall be included in all
   copies or substantial portions of the Software.

   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
   SOFTWARE.
*)

(** * Core Erlang: syntax

    A first-order fragment of Core Erlang, following the language of
    Lanese, Nishida, Palacios and Vidal, /A theory of reversibility for Erlang/
    (JLAMP 2018), Figure 1, with the following deliberate differences.

    - Environments are replaced by substitution: since the language is eager
      and first-order, variables are always bound to closed values, so
      substituting a value for a variable never captures.  A configuration is
      therefore an expression, not a pair (environment, expression).
    - Guards are omitted: a clause is [pat → e].  In Core Erlang guards may
      only call built-ins, so they can be recovered by an extra [case].
    - Tuples are omitted: they are encoded by lists ([VCons]).
    - Pids are not generated by a freshness side condition but allocated
      deterministically: a process keeps the number [n] of children it has
      already spawned and its [n]-th child gets the pid [n :: p].  Pids are
      then unique by construction whenever the initial pids are, and no
      restriction operator [ν] is needed.
    - [receive cls after e] is included (with an unspecified timeout, hence a
      timeout branch that may always be taken).  It is the only construct of
      the language offering a choice between receiving and computing, and it is
      what makes it possible to write observers.
    - [✓] ([ETick]) is an inert expression marking success; it is used by the
      testing predicate, not by programs.
    - [κ] ([EHole]) is the hole of Lanese et al.: the expression semantics
      answers a request to the system level and leaves a hole for the answer.
*)

From Stdlib.Unicode Require Import Utf8.
From Stdlib.Lists Require Import List.
Import ListNotations.
From stdpp Require Import base countable decidable list numbers.

(** ** Names *)

Definition var : Type := nat.
Definition atom : Type := nat.
Definition fname : Type := nat.
Definition bifname : Type := nat.

(** A pid is the path of the process in the spawn tree; [[]] is a root. *)
Definition pid : Type := list nat.

(** ** Values *)

Inductive val : Type :=
| VAtom (a : atom)
| VInt (z : Z)
| VPid (p : pid)
| VNil
| VCons (v1 v2 : val).

(** ** Patterns *)

Inductive pat : Type :=
| PVar (x : var)
| PAtom (a : atom)
| PInt (z : Z)
| PPid (p : pid)
| PNil
| PCons (q1 q2 : pat).

(** ** Decidability and countability of values and patterns *)

#[global] Instance val_eq_dec : EqDecision val.
Proof. solve_decision. Defined.

#[global] Instance pat_eq_dec : EqDecision pat.
Proof. solve_decision. Defined.

Definition vleaf : Type := (atom + Z + pid)%type.

#[global] Instance vleaf_eq_dec : EqDecision vleaf.
Proof. unfold vleaf. solve_decision. Defined.

#[global] Instance vleaf_countable : Countable vleaf.
Proof. unfold vleaf. apply _. Defined.

Fixpoint val_encode (v : val) : gen_tree (option vleaf) :=
  match v with
  | VAtom a => GenLeaf (Some (inl (inl a)))
  | VInt z => GenLeaf (Some (inl (inr z)))
  | VPid p => GenLeaf (Some (inr p))
  | VNil => GenLeaf None
  | VCons v1 v2 => GenNode 0 [val_encode v1; val_encode v2]
  end.

Fixpoint val_decode (t : gen_tree (option vleaf)) : option val :=
  match t with
  | GenLeaf (Some (inl (inl a))) => Some (VAtom a)
  | GenLeaf (Some (inl (inr z))) => Some (VInt z)
  | GenLeaf (Some (inr p)) => Some (VPid p)
  | GenLeaf None => Some VNil
  | GenNode 0 [t1; t2] =>
      match val_decode t1 with
      | Some v1 => match val_decode t2 with
                   | Some v2 => Some (VCons v1 v2)
                   | None => None
                   end
      | None => None
      end
  | GenNode _ _ => None
  end.

Lemma val_decode_encode v : val_decode (val_encode v) = Some v.
Proof. induction v; simpl; try done. by rewrite IHv1, IHv2. Qed.

#[global] Instance val_countable : Countable val.
Proof. refine (inj_countable val_encode val_decode val_decode_encode). Defined.

Fixpoint pat_encode (q : pat) : gen_tree (option vleaf) :=
  match q with
  | PVar x => GenNode 1 [GenLeaf (Some (inl (inl x)))]
  | PAtom a => GenLeaf (Some (inl (inl a)))
  | PInt z => GenLeaf (Some (inl (inr z)))
  | PPid p => GenLeaf (Some (inr p))
  | PNil => GenLeaf None
  | PCons q1 q2 => GenNode 0 [pat_encode q1; pat_encode q2]
  end.

Fixpoint pat_decode (t : gen_tree (option vleaf)) : option pat :=
  match t with
  | GenNode 1 [GenLeaf (Some (inl (inl x)))] => Some (PVar x)
  | GenLeaf (Some (inl (inl a))) => Some (PAtom a)
  | GenLeaf (Some (inl (inr z))) => Some (PInt z)
  | GenLeaf (Some (inr p)) => Some (PPid p)
  | GenLeaf None => Some PNil
  | GenNode 0 [t1; t2] =>
      match pat_decode t1 with
      | Some q1 => match pat_decode t2 with
                   | Some q2 => Some (PCons q1 q2)
                   | None => None
                   end
      | None => None
      end
  | GenNode _ _ => None
  end.

Lemma pat_decode_encode q : pat_decode (pat_encode q) = Some q.
Proof. induction q; simpl; try done. by rewrite IHq1, IHq2. Qed.

#[global] Instance pat_countable : Countable pat.
Proof. refine (inj_countable pat_encode pat_decode pat_decode_encode). Defined.

(** ** Expressions

    Clause lists and argument lists are mutual inductive types rather than
    [list]s: every traversal below is then a plain structural mutual fixpoint.
    [args_to_list] and [clauses_to_list] bridge to [list] when convenient.

    [EReceive] and [EReceiveAfter] are the receive without and with a timeout
    branch. *)

Inductive expr : Type :=
| EVar (x : var)
| EVal (v : val)
| ECons (e1 e2 : expr)
| ELet (x : var) (e1 e2 : expr)
| ECase (e : expr) (cls : clauses)
| EApply (f : fname) (es : args)
| ECall (op : bifname) (es : args)
| ESend (e1 e2 : expr)
| EReceive (cls : clauses)
| EReceiveAfter (cls : clauses) (a : expr)
| ESpawn (f : fname) (es : args)
| ESelf
| ETick
| EHole
with clauses : Type :=
| CNil
| CCons (q : pat) (e : expr) (cls : clauses)
with args : Type :=
| ANil
| ACons (e : expr) (es : args).

Notation "'✓ₑ'" := ETick.
Notation "'κ'" := EHole.

Fixpoint args_to_list (es : args) : list expr :=
  match es with ANil => [] | ACons e es' => e :: args_to_list es' end.

Fixpoint list_to_args (es : list expr) : args :=
  match es with [] => ANil | e :: es' => ACons e (list_to_args es') end.

Lemma args_to_list_to_args es : args_to_list (list_to_args es) = es.
Proof. induction es; simpl; by f_equal. Qed.

(** ** Countability of expressions *)

Definition eleaf : Type := (nat + val + pat)%type.

#[global] Instance eleaf_eq_dec : EqDecision eleaf.
Proof. unfold eleaf. solve_decision. Defined.

#[global] Instance eleaf_countable : Countable eleaf.
Proof. unfold eleaf. apply _. Defined.

Fixpoint expr_encode (e : expr) : gen_tree eleaf :=
  match e with
  | EVar x => GenNode 0 [GenLeaf (inl (inl x))]
  | EVal v => GenNode 1 [GenLeaf (inl (inr v))]
  | ECons e1 e2 => GenNode 2 [expr_encode e1; expr_encode e2]
  | ELet x e1 e2 => GenNode 3 [GenLeaf (inl (inl x)); expr_encode e1; expr_encode e2]
  | ECase e cls => GenNode 4 [expr_encode e; cls_encode cls]
  | EApply f es => GenNode 5 [GenLeaf (inl (inl f)); args_encode es]
  | ECall op es => GenNode 6 [GenLeaf (inl (inl op)); args_encode es]
  | ESend e1 e2 => GenNode 7 [expr_encode e1; expr_encode e2]
  | EReceive cls => GenNode 8 [cls_encode cls]
  | EReceiveAfter cls a => GenNode 9 [cls_encode cls; expr_encode a]
  | ESpawn f es => GenNode 10 [GenLeaf (inl (inl f)); args_encode es]
  | ESelf => GenNode 11 []
  | ETick => GenNode 12 []
  | EHole => GenNode 13 []
  end
with cls_encode (cls : clauses) : gen_tree eleaf :=
  match cls with
  | CNil => GenNode 20 []
  | CCons q e cls' => GenNode 21 [GenLeaf (inr q); expr_encode e; cls_encode cls']
  end
with args_encode (es : args) : gen_tree eleaf :=
  match es with
  | ANil => GenNode 22 []
  | ACons e es' => GenNode 23 [expr_encode e; args_encode es']
  end.

Fixpoint expr_decode (t : gen_tree eleaf) : option expr :=
  match t with
  | GenNode 0 [GenLeaf (inl (inl x))] => Some (EVar x)
  | GenNode 1 [GenLeaf (inl (inr v))] => Some (EVal v)
  | GenNode 2 [t1; t2] =>
      match expr_decode t1, expr_decode t2 with
      | Some e1, Some e2 => Some (ECons e1 e2)
      | _, _ => None
      end
  | GenNode 3 [GenLeaf (inl (inl x)); t1; t2] =>
      match expr_decode t1, expr_decode t2 with
      | Some e1, Some e2 => Some (ELet x e1 e2)
      | _, _ => None
      end
  | GenNode 4 [t1; t2] =>
      match expr_decode t1, cls_decode t2 with
      | Some e, Some cls => Some (ECase e cls)
      | _, _ => None
      end
  | GenNode 5 [GenLeaf (inl (inl f)); t2] =>
      match args_decode t2 with Some es => Some (EApply f es) | None => None end
  | GenNode 6 [GenLeaf (inl (inl op)); t2] =>
      match args_decode t2 with Some es => Some (ECall op es) | None => None end
  | GenNode 7 [t1; t2] =>
      match expr_decode t1, expr_decode t2 with
      | Some e1, Some e2 => Some (ESend e1 e2)
      | _, _ => None
      end
  | GenNode 8 [t1] =>
      match cls_decode t1 with Some cls => Some (EReceive cls) | None => None end
  | GenNode 9 [t1; t2] =>
      match cls_decode t1, expr_decode t2 with
      | Some cls, Some a => Some (EReceiveAfter cls a)
      | _, _ => None
      end
  | GenNode 10 [GenLeaf (inl (inl f)); t2] =>
      match args_decode t2 with Some es => Some (ESpawn f es) | None => None end
  | GenNode 11 [] => Some ESelf
  | GenNode 12 [] => Some ETick
  | GenNode 13 [] => Some EHole
  | _ => None
  end
with cls_decode (t : gen_tree eleaf) : option clauses :=
  match t with
  | GenNode 20 [] => Some CNil
  | GenNode 21 [GenLeaf (inr q); t1; t2] =>
      match expr_decode t1, cls_decode t2 with
      | Some e, Some cls => Some (CCons q e cls)
      | _, _ => None
      end
  | _ => None
  end
with args_decode (t : gen_tree eleaf) : option args :=
  match t with
  | GenNode 22 [] => Some ANil
  | GenNode 23 [t1; t2] =>
      match expr_decode t1, args_decode t2 with
      | Some e, Some es => Some (ACons e es)
      | _, _ => None
      end
  | _ => None
  end.

Lemma expr_decode_encode e : expr_decode (expr_encode e) = Some e
with cls_decode_encode cls : cls_decode (cls_encode cls) = Some cls
with args_decode_encode es : args_decode (args_encode es) = Some es.
Proof.
  - destruct e; simpl;
      repeat match goal with
        | |- context [expr_decode (expr_encode ?e)] => rewrite (expr_decode_encode e)
        | |- context [cls_decode (cls_encode ?c)] => rewrite (cls_decode_encode c)
        | |- context [args_decode (args_encode ?l)] => rewrite (args_decode_encode l)
        end; done.
  - destruct cls; simpl; [done |].
    rewrite (expr_decode_encode e), (cls_decode_encode cls). done.
  - destruct es; simpl; [done |].
    rewrite (expr_decode_encode e), (args_decode_encode es). done.
Qed.

Lemma expr_encode_inj e1 e2 : expr_encode e1 = expr_encode e2 → e1 = e2.
Proof.
  intros heq.
  assert (expr_decode (expr_encode e1) = expr_decode (expr_encode e2)) as h by by rewrite heq.
  rewrite (expr_decode_encode e1), (expr_decode_encode e2) in h. by simplify_eq.
Qed.

#[global] Instance expr_eq_dec : EqDecision expr.
Proof.
  intros e1 e2. destruct (decide (expr_encode e1 = expr_encode e2)) as [h | h].
  - left. by apply expr_encode_inj.
  - right. intros ->. by apply h.
Defined.

#[global] Instance expr_countable : Countable expr.
Proof. refine (inj_countable expr_encode expr_decode expr_decode_encode). Defined.

Lemma cls_encode_inj cls1 cls2 : cls_encode cls1 = cls_encode cls2 → cls1 = cls2.
Proof.
  intros heq.
  assert (cls_decode (cls_encode cls1) = cls_decode (cls_encode cls2)) as h by by rewrite heq.
  rewrite (cls_decode_encode cls1), (cls_decode_encode cls2) in h. by simplify_eq.
Qed.

#[global] Instance clauses_eq_dec : EqDecision clauses.
Proof.
  intros c1 c2. destruct (decide (cls_encode c1 = cls_encode c2)) as [h | h].
  - left. by apply cls_encode_inj.
  - right. intros ->. by apply h.
Defined.

#[global] Instance clauses_countable : Countable clauses.
Proof. refine (inj_countable cls_encode cls_decode cls_decode_encode). Defined.

Lemma args_encode_inj es1 es2 : args_encode es1 = args_encode es2 → es1 = es2.
Proof.
  intros heq.
  assert (args_decode (args_encode es1) = args_decode (args_encode es2)) as h by by rewrite heq.
  rewrite (args_decode_encode es1), (args_decode_encode es2) in h. by simplify_eq.
Qed.

#[global] Instance args_eq_dec : EqDecision args.
Proof.
  intros c1 c2. destruct (decide (args_encode c1 = args_encode c2)) as [h | h].
  - left. by apply args_encode_inj.
  - right. intros ->. by apply h.
Defined.

#[global] Instance args_countable : Countable args.
Proof. refine (inj_countable args_encode args_decode args_decode_encode). Defined.

(** ** Substitution

    [σ] is a finite list of bindings of closed values.  Descending under a
    binder removes the bound variables from [σ]: patterns of Core Erlang bind
    fresh variables, but being hygienic here costs nothing. *)

Definition sub : Type := list (var * val).

Fixpoint sub_lookup (σ : sub) (x : var) : option val :=
  match σ with
  | [] => None
  | (y, v) :: σ' => if decide (x = y) then Some v else sub_lookup σ' x
  end.

Definition sub_remove (xs : list var) (σ : sub) : sub :=
  filter (λ b, ¬ (b.1 ∈ xs)) σ.

Fixpoint pat_vars (q : pat) : list var :=
  match q with
  | PVar x => [x]
  | PCons q1 q2 => pat_vars q1 ++ pat_vars q2
  | _ => []
  end.

Fixpoint subst (σ : sub) (e : expr) : expr :=
  match e with
  | EVar x => match sub_lookup σ x with Some v => EVal v | None => EVar x end
  | EVal v => EVal v
  | ECons e1 e2 => ECons (subst σ e1) (subst σ e2)
  | ELet x e1 e2 => ELet x (subst σ e1) (subst (sub_remove [x] σ) e2)
  | ECase e cls => ECase (subst σ e) (subst_cls σ cls)
  | EApply f es => EApply f (subst_args σ es)
  | ECall op es => ECall op (subst_args σ es)
  | ESend e1 e2 => ESend (subst σ e1) (subst σ e2)
  | EReceive cls => EReceive (subst_cls σ cls)
  | EReceiveAfter cls a => EReceiveAfter (subst_cls σ cls) (subst σ a)
  | ESpawn f es => ESpawn f (subst_args σ es)
  | ESelf => ESelf
  | ETick => ETick
  | EHole => EHole
  end
with subst_cls (σ : sub) (cls : clauses) : clauses :=
  match cls with
  | CNil => CNil
  | CCons q e cls' => CCons q (subst (sub_remove (pat_vars q) σ) e) (subst_cls σ cls')
  end
with subst_args (σ : sub) (es : args) : args :=
  match es with
  | ANil => ANil
  | ACons e es' => ACons (subst σ e) (subst_args σ es')
  end.

(** ** Filling the hole [κ] *)

Fixpoint hfill (e : expr) (u : expr) : expr :=
  match e with
  | EHole => u
  | EVar x => EVar x
  | EVal v => EVal v
  | ECons e1 e2 => ECons (hfill e1 u) (hfill e2 u)
  | ELet x e1 e2 => ELet x (hfill e1 u) (hfill e2 u)
  | ECase e cls => ECase (hfill e u) (hfill_cls cls u)
  | EApply f es => EApply f (hfill_args es u)
  | ECall op es => ECall op (hfill_args es u)
  | ESend e1 e2 => ESend (hfill e1 u) (hfill e2 u)
  | EReceive cls => EReceive (hfill_cls cls u)
  | EReceiveAfter cls a => EReceiveAfter (hfill_cls cls u) (hfill a u)
  | ESpawn f es => ESpawn f (hfill_args es u)
  | ESelf => ESelf
  | ETick => ETick
  end
with hfill_cls (cls : clauses) (u : expr) : clauses :=
  match cls with
  | CNil => CNil
  | CCons q e cls' => CCons q (hfill e u) (hfill_cls cls' u)
  end
with hfill_args (es : args) (u : expr) : args :=
  match es with
  | ANil => ANil
  | ACons e es' => ACons (hfill e u) (hfill_args es' u)
  end.

(** ** Pattern matching *)

Fixpoint pat_match (q : pat) (v : val) : option sub :=
  match q, v with
  | PVar x, _ => Some [(x, v)]
  | PAtom a, VAtom b => if decide (a = b) then Some [] else None
  | PInt z, VInt z' => if decide (z = z') then Some [] else None
  | PPid p, VPid p' => if decide (p = p') then Some [] else None
  | PNil, VNil => Some []
  | PCons q1 q2, VCons v1 v2 =>
      match pat_match q1 v1, pat_match q2 v2 with
      | Some σ1, Some σ2 => Some (σ1 ++ σ2)
      | _, _ => None
      end
  | _, _ => None
  end.

(** [match_cls cls v] is the body of the first clause of [cls] matching [v],
    instantiated by the matching substitution. *)
Fixpoint match_cls (cls : clauses) (v : val) : option expr :=
  match cls with
  | CNil => None
  | CCons q e cls' =>
      match pat_match q v with
      | Some σ => Some (subst σ e)
      | None => match_cls cls' v
      end
  end.
